# Generated by Django 4.0.6 on 2022-08-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb_in_present', models.CharField(max_length=255)),
                ('english_translation', models.CharField(max_length=255)),
                ('french_translation', models.CharField(blank=True, max_length=255, null=True)),
                ('past_participle', models.CharField(blank=True, max_length=255, null=True)),
                ('simple_past', models.CharField(blank=True, max_length=255, null=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
