# Generated by Django 4.0.6 on 2022-07-28 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verb',
            old_name='verb_in_past_participle',
            new_name='past_participle',
        ),
        migrations.RenameField(
            model_name='verb',
            old_name='verb_in_simple_past',
            new_name='simple_past',
        ),
    ]
