# Generated by Django 4.0.6 on 2022-07-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
