# Generated by Django 4.0.6 on 2022-07-28 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_is_validated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_validated',
            new_name='approved',
        ),
    ]
