# Generated by Django 4.0.6 on 2022-08-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direct_pronoun', models.CharField(blank=True, default='', max_length=255)),
                ('german_translation', models.CharField(max_length=255)),
                ('english_translation', models.CharField(max_length=255)),
                ('french_translation', models.CharField(blank=True, default='', max_length=255)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
